name: aurora
description: Test image for aurora

base-image: ghcr.io/ublue-os/aurora
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - main.sh

  - type: dnf
    install:
      - taidan

  - type: signing

